apiVersion: v1
kind: Service
metadata:
  name: qubit-engine
  namespace: quantum-system
spec:
  selector:
    app: qubit-engine
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc
