apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - engine-deployment.yaml
  - engine-service.yaml

images:
  - name: qubit-engine:prod
    newName: qubit-engine
    newTag: latest
