{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.backendSecretName }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager # Assumes ClusterSecretStore exists
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.backendSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: {{ .Values.externalSecrets.remoteKey }}
      property: api-key
{{- end }}
